from fastapi import APIRouter, UploadFile, File, Depends, Form
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.models.source import SourceDocument
from app.models.chunk import ContentChunk
from app.services.pdf_service import extract_text_from_pdf
from app.services.text_cleaner import clean_extracted_text
from app.services.chunking_service import chunk_text
from app.schemas.ingest_schema import IngestResponse
import logging

router = APIRouter(prefix="/ingest", tags=["Ingest"])
logger = logging.getLogger(__name__)

@router.post("/", response_model=IngestResponse)
async def ingest_pdf(
    file: UploadFile = File(...),
    subject: str = Form(None),
    grade: int = Form(None),
    db: Session = Depends(get_db)
):
    """
    Ingests a PDF file, extracts text, cleans it, chunks it, and stores it in the database.
    """
    logger.info(f"Received PDF for ingestion: {file.filename}")
    
    # 1. Extract text
    raw_text = extract_text_from_pdf(file)
    
    # 2. Clean text
    clean_text = clean_extracted_text(raw_text)
    
    # 3. Create Source Document record
    new_source = SourceDocument(
        subject=subject,
        grade=grade,
        filename=file.filename
    )
    db.add(new_source)
    db.flush() # Populate new_source.source_id generated by default
    
    # 4. Chunk text
    chunks = chunk_text(clean_text)
    
    # 5. Store chunks
    for chunk_text_content in chunks:
        new_chunk = ContentChunk(
            source_id=new_source.source_id,
            text=chunk_text_content,
            topic=subject # Using subject as topic fallback for simplicity
        )
        db.add(new_chunk)
    
    db.commit()
    logger.info(f"Ingestion complete for {file.filename}. Created {len(chunks)} chunks.")
    
    return IngestResponse(
        source_id=new_source.source_id,
        chunks_created=len(chunks)
    )
